[check_url]
command_line = "timeout {timeout_s}s curl {url}"

[top]
command_line = "top -n 1"

[df]
command_line = "df -h"

[ps]
command_line = "ps -efww"

[namenode_]
command_line = "abcd.py {arg1}"

[escape_test1]
command_line = "echo {key1} && echo {key2} || echo hi"

[escape_test2]
command_line = "echo $my_env"

[return_error_code_1]
command_line = "echo error >&2; exit 1"
