[alert_infos_to_kafka]
kind = "kafka"
# TODO: handle critical_only?
#critical_only = false
[alert_infos_to_kafka.kafka]
bootstrap_servers = "localhost:9092"
topic = "infos"

#[alert_infos_to_stdout]
#kind = "stdout"
