#[check_datanode_ui]
#host_group_name = "datanode"
#description = "DATANODE::Check Datanode UI"
#command_name = "check_url"
#store_name = "alert_infos_to_kafka"
#interval_s = 60
#retry_interval_s = 25
#max_check_attempts = 3
#notification_interval_s = 60
#critical = true
#
#[check_datanode_ui.param]
#timeout_s = 5
#url = "http://localhost:9864"


[check_top]
host_group_name = "all"
description = "ALL::Check top"
command_name = "top"
store_name = "alert_infos_to_stdout"
interval_s = 3
retry_interval_s = 25
max_check_attempts = 3
notification_interval_s = 60
critical = true

[check_df]
host_group_name = "all"
description = "ALL::Check df"
command_name = "df"
store_name = "alert_infos_to_stdout"
interval_s = 5
retry_interval_s = 25
max_check_attempts = 3
notification_interval_s = 60
critical = true
