#[check_datanode_ui]
#host_group_name = "datanode"
#description = "DATANODE::Check Datanode UI"
#command_name = "check_url"
#store_name = "alert_infos_to_kafka"
#interval_s = 60
#retry_interval_s = 25
#max_retries = 3
#notification_interval_s = 60
#critical = true
#
#[check_datanode_ui.param]
#timeout_s = 5
#url = "http://localhost:9864"


#[check_top]
#host_group_name = "all"
#description = "ALL::Check escape_test1"
#command_name = "escape_test1"
#store_name = "alert_infos_to_stdout"
#crontab = "1/3 * * * * * *" # every 3s
#retry_interval_s = 25
#max_retries = 3
#notification_interval_s = 60
#critical = true
#
#[check_df]
#host_group_name = "all"
#description = "ALL::Check escape_test2"
#command_name = "escape_test2"
#store_name = "alert_infos_to_stdout"
#crontab = "1/5 * * * * * *"
#retry_interval_s = 25
#max_retries = 3
#notification_interval_s = 60
#critical = true

[check_top]
host_group_name = "all"
description = "ALL::Check escape_test1"
store_name = "alert_infos_to_kafka"
crontab = "1/3 * * * * * *" # every 3s
retry_interval_s = 25
max_retries = 3
notification_interval_s = 60
critical = true
[check_top.command]
name = "escape_test1"
[check_top.command.param]
key1 = "hello"
key2 = "world"


[check_df]
host_group_name = "all"
description = "ALL::Check escape_test2"
store_name = "alert_infos_to_kafka"
crontab = "1/5 * * * * * *"
retry_interval_s = 25
max_retries = 3
notification_interval_s = 60
critical = true
[check_df.command]
name = "df"


[return_error_code]
host_group_name = "all"
description = "ALL::Return just error code"
store_name = "alert_infos_to_kafka"
crontab = "1/1 * * * * * *"
retry_interval_s = 1
max_retries = 1
notification_interval_s = 0
critical = true
[return_error_code.command]
name = "return_error_code_1"


#[check_ps]
#host_group_name = "all"
#description = "ALL::Check escape_test2"
#command_name = "ps"
#store_name = "alert_infos_to_stdout"
#crontab = "1/5 * * * * * *"
#retry_interval_s = 25
#max_retries = 3
#notification_interval_s = 60
#critical = true
