[alert_infos_to_kafka]
kind = "kafka"
[alert_infos_to_kafka.param]
"bootstrap.servers" = "localhost:9092"
topic = "alert-infos"
# TODO: handle critical_only?
critical_only = false

#[alert_infos_to_stdout]
#kind = "stdout"
